const nepalData = {
  provinces: [
    { id: "province1", name: "Province 1" },
    { id: "madhesh", name: "Madhesh Province" },
    { id: "bagmati", name: "Bagmati Province" },
    { id: "gandaki", name: "Gandaki Province" },
    { id: "lumbini", name: "Lumbini Province" },
    { id: "karnali", name: "Karnali Province" },
    { id: "sudurpaschim", name: "Sudurpaschim Province" },
  ],
  districts: {
    province1: [
      { id: "taplejung", name: "Taplejung" },
      { id: "panchthar", name: "Panchthar" },
      { id: "ilam", name: "Ilam" },
      { id: "jhapa", name: "Jhapa" },
      { id: "morang", name: "Morang" },
      { id: "sunsari", name: "Sunsari" },
      { id: "dhankuta", name: "Dhankuta" },
      { id: "terhathum", name: "Terhathum" },
      { id: "sankhuwasabha", name: "Sankhuwasabha" },
      { id: "bhojpur", name: "Bhojpur" },
      { id: "solukhumbu", name: "Solukhumbu" },
      { id: "okhaldhunga", name: "Okhaldhunga" },
      { id: "khotang", name: "Khotang" },
      { id: "udayapur", name: "Udayapur" },
    ],
    madhesh: [
      { id: "saptari", name: "Saptari" },
      { id: "siraha", name: "Siraha" },
      { id: "dhanusa", name: "Dhanusa" },
      { id: "mahottari", name: "Mahottari" },
      { id: "sarlahi", name: "Sarlahi" },
      { id: "rautahat", name: "Rautahat" },
      { id: "bara", name: "Bara" },
      { id: "parsa", name: "Parsa" },
    ],
    bagmati: [
      { id: "dolakha", name: "Dolakha" },
      { id: "sindhupalchok", name: "Sindhupalchok" },
      { id: "rasuwa", name: "Rasuwa" },
      { id: "dhading", name: "Dhading" },
      { id: "nuwakot", name: "Nuwakot" },
      { id: "kathmandu", name: "Kathmandu" },
      { id: "bhaktapur", name: "Bhaktapur" },
      { id: "lalitpur", name: "Lalitpur" },
      { id: "kavrepalanchok", name: "Kavrepalanchok" },
      { id: "ramechhap", name: "Ramechhap" },
      { id: "sindhuli", name: "Sindhuli" },
      { id: "makwanpur", name: "Makwanpur" },
      { id: "chitwan", name: "Chitwan" },
    ],
    gandaki: [
      { id: "gorkha", name: "Gorkha" },
      { id: "manang", name: "Manang" },
      { id: "mustang", name: "Mustang" },
      { id: "myagdi", name: "Myagdi" },
      { id: "kaski", name: "Kaski" },
      { id: "lamjung", name: "Lamjung" },
      { id: "tanahu", name: "Tanahu" },
      { id: "nawalparasi_east", name: "Nawalparasi East" },
      { id: "syangja", name: "Syangja" },
      { id: "parbat", name: "Parbat" },
      { id: "baglung", name: "Baglung" },
    ],
    lumbini: [
      { id: "rukum_east", name: "Rukum East" },
      { id: "rolpa", name: "Rolpa" },
      { id: "pyuthan", name: "Pyuthan" },
      { id: "gulmi", name: "Gulmi" },
      { id: "arghakhanchi", name: "Arghakhanchi" },
      { id: "palpa", name: "Palpa" },
      { id: "nawalparasi_west", name: "Nawalparasi West" },
      { id: "rupandehi", name: "Rupandehi" },
      { id: "kapilvastu", name: "Kapilvastu" },
      { id: "dang", name: "Dang" },
      { id: "banke", name: "Banke" },
      { id: "bardiya", name: "Bardiya" },
    ],
    karnali: [
      { id: "dolpa", name: "Dolpa" },
      { id: "mugu", name: "Mugu" },
      { id: "humla", name: "Humla" },
      { id: "jumla", name: "Jumla" },
      { id: "kalikot", name: "Kalikot" },
      { id: "dailekh", name: "Dailekh" },
      { id: "jajarkot", name: "Jajarkot" },
      { id: "rukum_west", name: "Rukum West" },
      { id: "salyan", name: "Salyan" },
      { id: "surkhet", name: "Surkhet" },
    ],
    sudurpaschim: [
      { id: "bajura", name: "Bajura" },
      { id: "bajhang", name: "Bajhang" },
      { id: "darchula", name: "Darchula" },
      { id: "baitadi", name: "Baitadi" },
      { id: "dadeldhura", name: "Dadeldhura" },
      { id: "doti", name: "Doti" },
      { id: "achham", name: "Achham" },
      { id: "kailali", name: "Kailali" },
      { id: "kanchanpur", name: "Kanchanpur" },
    ],
  },
  localLevels: {
    // Province 1 - Key districts
    jhapa: [
      { id: "mechinagar", name: "Mechinagar Municipality", type: "municipality" },
      { id: "birtamod", name: "Birtamod Municipality", type: "municipality" },
      { id: "damak", name: "Damak Municipality", type: "municipality" },
      { id: "kankai", name: "Kankai Municipality", type: "municipality" },
      { id: "bhadrapur", name: "Bhadrapur Municipality", type: "municipality" },
      { id: "arjundhara", name: "Arjundhara Municipality", type: "municipality" },
      { id: "shivasatakshi", name: "Shivasatakshi Municipality", type: "municipality" },
      { id: "buddhashanti", name: "Buddhashanti Rural Municipality", type: "rural-municipality" },
      { id: "kachankawal", name: "Kachankawal Rural Municipality", type: "rural-municipality" },
      { id: "jhapa", name: "Jhapa Rural Municipality", type: "rural-municipality" },
      { id: "gauriganj", name: "Gauriganj Rural Municipality", type: "rural-municipality" },
      { id: "barhadashi", name: "Barhadashi Rural Municipality", type: "rural-municipality" },
      { id: "haldibari", name: "Haldibari Rural Municipality", type: "rural-municipality" },
      { id: "kmal", name: "Kamal Rural Municipality", type: "rural-municipality" },
    ],
    morang: [
      { id: "biratnagar", name: "Biratnagar Metropolitan City", type: "metropolitan" },
      { id: "sundarharaicha", name: "Sundarharaicha Municipality", type: "municipality" },
      { id: "rangeli", name: "Rangeli Municipality", type: "municipality" },
      { id: "pathari_sanischare", name: "Pathari-Sanischare Municipality", type: "municipality" },
      { id: "letang", name: "Letang Municipality", type: "municipality" },
      { id: "ratuwamai", name: "Ratuwamai Municipality", type: "municipality" },
      { id: "urlabari", name: "Urlabari Municipality", type: "municipality" },
      { id: "sunawarshi", name: "Sunawarshi Municipality", type: "municipality" },
      { id: "belbari", name: "Belbari Municipality", type: "municipality" },
      { id: "kanepokhari", name: "Kanepokhari Rural Municipality", type: "rural-municipality" },
      { id: "gramthan", name: "Gramthan Rural Municipality", type: "rural-municipality" },
      { id: "budhiganga", name: "Budhiganga Rural Municipality", type: "rural-municipality" },
      { id: "katahari", name: "Katahari Rural Municipality", type: "rural-municipality" },
      { id: "dhanpalthan", name: "Dhanpalthan Rural Municipality", type: "rural-municipality" },
      { id: "kerabari", name: "Kerabari Rural Municipality", type: "rural-municipality" },
      { id: "miklajung", name: "Miklajung Rural Municipality", type: "rural-municipality" },
      { id: "jahada", name: "Jahada Rural Municipality", type: "rural-municipality" },
    ],
    sunsari: [
      { id: "dharan", name: "Dharan Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "itahari", name: "Itahari Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "inaruwa", name: "Inaruwa Municipality", type: "municipality" },
      { id: "duhabi", name: "Duhabi Municipality", type: "municipality" },
      { id: "ramdhuni", name: "Ramdhuni Municipality", type: "municipality" },
      { id: "barahchhetra", name: "Barahchhetra Municipality", type: "municipality" },
      { id: "harinagar", name: "Harinagar Rural Municipality", type: "rural-municipality" },
      { id: "bhokraha", name: "Bhokraha Narasimha Rural Municipality", type: "rural-municipality" },
      { id: "koshi", name: "Koshi Rural Municipality", type: "rural-municipality" },
      { id: "gadhi", name: "Gadhi Rural Municipality", type: "rural-municipality" },
      { id: "dewanganj", name: "Dewanganj Rural Municipality", type: "rural-municipality" },
      { id: "barju", name: "Barju Rural Municipality", type: "rural-municipality" },
    ],
    // More Province 1 districts
    taplejung: [
      { id: "phungling", name: "Phungling Municipality", type: "municipality" },
      {
        id: "aathrai_triveni",
        name: "Aathrai Triveni Rural Municipality",
        type: "rural-municipality",
      },
      { id: "sidingba", name: "Sidingba Rural Municipality", type: "rural-municipality" },
      { id: "faktanglung", name: "Faktanglung Rural Municipality", type: "rural-municipality" },
      { id: "mikwakhola", name: "Mikwakhola Rural Municipality", type: "rural-municipality" },
      { id: "meringden", name: "Meringden Rural Municipality", type: "rural-municipality" },
      { id: "maiwakhola", name: "Maiwakhola Rural Municipality", type: "rural-municipality" },
      {
        id: "pathibhara_yangwarak",
        name: "Pathibhara Yangwarak Rural Municipality",
        type: "rural-municipality",
      },
      { id: "sirijangha", name: "Sirijangha Rural Municipality", type: "rural-municipality" },
    ],
    panchthar: [
      { id: "phidim", name: "Phidim Municipality", type: "municipality" },
      { id: "phalelung", name: "Phalelung Rural Municipality", type: "rural-municipality" },
      { id: "falgunanda", name: "Falgunanda Rural Municipality", type: "rural-municipality" },
      { id: "hilihang", name: "Hilihang Rural Municipality", type: "rural-municipality" },
      { id: "kummayak", name: "Kummayak Rural Municipality", type: "rural-municipality" },
      { id: "miklajung", name: "Miklajung Rural Municipality", type: "rural-municipality" },
      { id: "tumbewa", name: "Tumbewa Rural Municipality", type: "rural-municipality" },
      { id: "yangwarak", name: "Yangwarak Rural Municipality", type: "rural-municipality" },
    ],
    ilam: [
      { id: "ilam", name: "Ilam Municipality", type: "municipality" },
      { id: "deumai", name: "Deumai Municipality", type: "municipality" },
      { id: "mai", name: "Mai Municipality", type: "municipality" },
      { id: "suryodaya", name: "Suryodaya Municipality", type: "municipality" },
      { id: "phakphokthum", name: "Phakphokthum Rural Municipality", type: "rural-municipality" },
      { id: "mai_jogmai", name: "Mai Jogmai Rural Municipality", type: "rural-municipality" },
      { id: "chulachuli", name: "Chulachuli Rural Municipality", type: "rural-municipality" },
      { id: "rong", name: "Rong Rural Municipality", type: "rural-municipality" },
      { id: "mangsebung", name: "Mangsebung Rural Municipality", type: "rural-municipality" },
      { id: "sandakpur", name: "Sandakpur Rural Municipality", type: "rural-municipality" },
    ],
    dhankuta: [
      { id: "dhankuta", name: "Dhankuta Municipality", type: "municipality" },
      { id: "pakhribas", name: "Pakhribas Municipality", type: "municipality" },
      { id: "mahalaxmi", name: "Mahalaxmi Municipality", type: "municipality" },
      { id: "sangurigadhi", name: "Sangurigadhi Rural Municipality", type: "rural-municipality" },
      { id: "sahidbhumi", name: "Sahidbhumi Rural Municipality", type: "rural-municipality" },
      { id: "chaubise", name: "Chaubise Rural Municipality", type: "rural-municipality" },
      {
        id: "khalsa_chhintang_sahidbhumi",
        name: "Khalsa Chhintang Sahidbhumi Rural Municipality",
        type: "rural-municipality",
      },
    ],
    terhathum: [
      { id: "myanglung", name: "Myanglung Municipality", type: "municipality" },
      { id: "laligurans", name: "Laligurans Municipality", type: "municipality" },
      { id: "aathrai", name: "Aathrai Rural Municipality", type: "rural-municipality" },
      { id: "chhathar", name: "Chhathar Rural Municipality", type: "rural-municipality" },
      { id: "phedap", name: "Phedap Rural Municipality", type: "rural-municipality" },
      { id: "menchhayayem", name: "Menchhayayem Rural Municipality", type: "rural-municipality" },
    ],
    sankhuwasabha: [
      { id: "chainpur", name: "Chainpur Municipality", type: "municipality" },
      { id: "dharmadevi", name: "Dharmadevi Municipality", type: "municipality" },
      { id: "khandbari", name: "Khandbari Municipality", type: "municipality" },
      { id: "madi", name: "Madi Municipality", type: "municipality" },
      { id: "panchkhapan", name: "Panchkhapan Municipality", type: "municipality" },
      { id: "bhot_khola", name: "Bhot Khola Rural Municipality", type: "rural-municipality" },
      { id: "chichila", name: "Chichila Rural Municipality", type: "rural-municipality" },
      { id: "makalu", name: "Makalu Rural Municipality", type: "rural-municipality" },
      { id: "savapokhari", name: "Savapokhari Rural Municipality", type: "rural-municipality" },
      { id: "silichong", name: "Silichong Rural Municipality", type: "rural-municipality" },
    ],
    bhojpur: [
      { id: "bhojpur", name: "Bhojpur Municipality", type: "municipality" },
      { id: "shadananda", name: "Shadananda Municipality", type: "municipality" },
      { id: "tyamke_maiyun", name: "Tyamke Maiyun Rural Municipality", type: "rural-municipality" },
      { id: "ramprasad_rai", name: "Ramprasad Rai Rural Municipality", type: "rural-municipality" },
      { id: "arun", name: "Arun Rural Municipality", type: "rural-municipality" },
      { id: "pauwadungma", name: "Pauwadungma Rural Municipality", type: "rural-municipality" },
      { id: "salpasilichho", name: "Salpasilichho Rural Municipality", type: "rural-municipality" },
      { id: "aamchok", name: "Aamchok Rural Municipality", type: "rural-municipality" },
      { id: "hatuwagadhi", name: "Hatuwagadhi Rural Municipality", type: "rural-municipality" },
    ],
    solukhumbu: [
      { id: "solududhkunda", name: "Solududhkunda Municipality", type: "municipality" },
      {
        id: "khumbu_pasang_lhamu",
        name: "Khumbu Pasang Lhamu Rural Municipality",
        type: "rural-municipality",
      },
      {
        id: "thulung_dudhkoshi",
        name: "Thulung Dudhkoshi Rural Municipality",
        type: "rural-municipality",
      },
      { id: "mahakulung", name: "Mahakulung Rural Municipality", type: "rural-municipality" },
      { id: "sotang", name: "Sotang Rural Municipality", type: "rural-municipality" },
      {
        id: "mapya_dudhkoshi",
        name: "Mapya Dudhkoshi Rural Municipality",
        type: "rural-municipality",
      },
      {
        id: "khumbupasanglhamu",
        name: "Khumbupasanglhamu Rural Municipality",
        type: "rural-municipality",
      },
      { id: "necha_salyan", name: "Necha Salyan Rural Municipality", type: "rural-municipality" },
    ],
    okhaldhunga: [
      { id: "siddhicharan", name: "Siddhicharan Municipality", type: "municipality" },
      { id: "manebhanjyang", name: "Manebhanjyang Rural Municipality", type: "rural-municipality" },
      { id: "champadevi", name: "Champadevi Rural Municipality", type: "rural-municipality" },
      {
        id: "chisankhugadhi",
        name: "Chisankhugadhi Rural Municipality",
        type: "rural-municipality",
      },
      { id: "khiji_demba", name: "Khiji Demba Rural Municipality", type: "rural-municipality" },
      { id: "likhu", name: "Likhu Rural Municipality", type: "rural-municipality" },
      { id: "molung", name: "Molung Rural Municipality", type: "rural-municipality" },
      { id: "sunkoshi", name: "Sunkoshi Rural Municipality", type: "rural-municipality" },
    ],
    khotang: [
      {
        id: "diktel_rupakot_majhuwagadhi",
        name: "Diktel Rupakot Majhuwagadhi Municipality",
        type: "municipality",
      },
      { id: "halesi_tuwachung", name: "Halesi Tuwachung Municipality", type: "municipality" },
      { id: "aiselukharka", name: "Aiselukharka Rural Municipality", type: "rural-municipality" },
      { id: "jantedhunga", name: "Jantedhunga Rural Municipality", type: "rural-municipality" },
      { id: "khotehang", name: "Khotehang Rural Municipality", type: "rural-municipality" },
      { id: "kepilasgadhi", name: "Kepilasgadhi Rural Municipality", type: "rural-municipality" },
      { id: "diprung", name: "Diprung Rural Municipality", type: "rural-municipality" },
      { id: "sakela", name: "Sakela Rural Municipality", type: "rural-municipality" },
      { id: "barahapokhari", name: "Barahapokhari Rural Municipality", type: "rural-municipality" },
      { id: "rawabesi", name: "Rawabesi Rural Municipality", type: "rural-municipality" },
    ],
    udayapur: [
      { id: "triyuga", name: "Triyuga Municipality", type: "municipality" },
      { id: "katari", name: "Katari Municipality", type: "municipality" },
      { id: "chaudandigadhi", name: "Chaudandigadhi Municipality", type: "municipality" },
      { id: "belaka", name: "Belaka Municipality", type: "municipality" },
      { id: "udayapurgadhi", name: "Udayapurgadhi Rural Municipality", type: "rural-municipality" },
      { id: "tapli", name: "Tapli Rural Municipality", type: "rural-municipality" },
      { id: "rautamai", name: "Rautamai Rural Municipality", type: "rural-municipality" },
      { id: "limchungbung", name: "Limchungbung Rural Municipality", type: "rural-municipality" },
    ],

    // Madhesh Province - Key Districts
    dhanusa: [
      { id: "janakpur", name: "Janakpur Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "chhireshwarnath", name: "Chhireshwarnath Municipality", type: "municipality" },
      { id: "ganeshman_charnath", name: "Ganeshman Charnath Municipality", type: "municipality" },
      { id: "dhanusadham", name: "Dhanusadham Municipality", type: "municipality" },
      { id: "mithila", name: "Mithila Municipality", type: "municipality" },
      { id: "sabaila", name: "Sabaila Municipality", type: "municipality" },
      { id: "hansapur", name: "Hansapur Municipality", type: "municipality" },
      { id: "kamala", name: "Kamala Municipality", type: "municipality" },
      { id: "aurahi", name: "Aurahi Rural Municipality", type: "rural-municipality" },
      { id: "bateshwar", name: "Bateshwar Rural Municipality", type: "rural-municipality" },
      { id: "janaknandini", name: "Janaknandini Rural Municipality", type: "rural-municipality" },
      { id: "lakshminya", name: "Lakshminya Rural Municipality", type: "rural-municipality" },
      {
        id: "mukhiyapatti",
        name: "Mukhiyapatti Musaharniya Rural Municipality",
        type: "rural-municipality",
      },
    ],
    sarlahi: [
      { id: "malangwa", name: "Malangwa Municipality", type: "municipality" },
      { id: "barahathwa", name: "Barahathwa Municipality", type: "municipality" },
      { id: "godaita", name: "Godaita Municipality", type: "municipality" },
      { id: "ishworpur", name: "Ishworpur Municipality", type: "municipality" },
      { id: "lalbandi", name: "Lalbandi Municipality", type: "municipality" },
      { id: "balara", name: "Balara Municipality", type: "municipality" },
      { id: "bagmati", name: "Bagmati Municipality", type: "municipality" },
      { id: "haripur", name: "Haripur Municipality", type: "municipality" },
      { id: "haripurwa", name: "Haripurwa Municipality", type: "municipality" },
      { id: "kabilasi", name: "Kabilasi Municipality", type: "municipality" },
      { id: "chakraghatta", name: "Chakraghatta Rural Municipality", type: "rural-municipality" },
      { id: "basbariya", name: "Basbariya Rural Municipality", type: "rural-municipality" },
    ],
    // More Madhesh Province districts
    saptari: [
      { id: "rajbiraj", name: "Rajbiraj Municipality", type: "municipality" },
      { id: "kanchanrup", name: "Kanchanrup Municipality", type: "municipality" },
      { id: "dakneshwori", name: "Dakneshwori Municipality", type: "municipality" },
      { id: "bodebarsain", name: "Bodebarsain Municipality", type: "municipality" },
      { id: "khadak", name: "Khadak Municipality", type: "municipality" },
      { id: "shambhunath", name: "Shambhunath Municipality", type: "municipality" },
      { id: "surunga", name: "Surunga Municipality", type: "municipality" },
      { id: "hanumannagar", name: "Hanumannagar Kankalini Municipality", type: "municipality" },
      { id: "saptakoshi", name: "Saptakoshi Municipality", type: "municipality" },
      {
        id: "agnisaira_krishnasavaran",
        name: "Agnisaira Krishnasavaran Rural Municipality",
        type: "rural-municipality",
      },
      { id: "rupani", name: "Rupani Rural Municipality", type: "rural-municipality" },
      { id: "mahadeva", name: "Mahadeva Rural Municipality", type: "rural-municipality" },
      { id: "tirhut", name: "Tirhut Rural Municipality", type: "rural-municipality" },
      {
        id: "tilathi_koiladi",
        name: "Tilathi Koiladi Rural Municipality",
        type: "rural-municipality",
      },
      { id: "chinnamasta", name: "Chinnamasta Rural Municipality", type: "rural-municipality" },
      { id: "belhi_chapena", name: "Belhi Chapena Rural Municipality", type: "rural-municipality" },
      { id: "bishnupur", name: "Bishnupur Rural Municipality", type: "rural-municipality" },
      { id: "rajgadh", name: "Rajgadh Rural Municipality", type: "rural-municipality" },
    ],
    siraha: [
      { id: "siraha", name: "Siraha Municipality", type: "municipality" },
      { id: "lahan", name: "Lahan Municipality", type: "municipality" },
      { id: "dhangadhimai", name: "Dhangadhimai Municipality", type: "municipality" },
      { id: "golbazar", name: "Golbazar Municipality", type: "municipality" },
      { id: "mirchaiya", name: "Mirchaiya Municipality", type: "municipality" },
      { id: "kalyanpur", name: "Kalyanpur Municipality", type: "municipality" },
      { id: "karjanha", name: "Karjanha Municipality", type: "municipality" },
      { id: "sukhipur", name: "Sukhipur Municipality", type: "municipality" },
      { id: "bhagwanpur", name: "Bhagwanpur Rural Municipality", type: "rural-municipality" },
      { id: "aurahi", name: "Aurahi Rural Municipality", type: "rural-municipality" },
      { id: "naraha", name: "Naraha Rural Municipality", type: "rural-municipality" },
      { id: "arnama", name: "Arnama Rural Municipality", type: "rural-municipality" },
      { id: "bariyarpatti", name: "Bariyarpatti Rural Municipality", type: "rural-municipality" },
      {
        id: "laxmipur_patari",
        name: "Laxmipur Patari Rural Municipality",
        type: "rural-municipality",
      },
      {
        id: "sakhuwanankarkatti",
        name: "Sakhuwanankarkatti Rural Municipality",
        type: "rural-municipality",
      },
      { id: "bishnupur", name: "Bishnupur Rural Municipality", type: "rural-municipality" },
      { id: "navrajpur", name: "Navrajpur Rural Municipality", type: "rural-municipality" },
    ],
    mahottari: [
      { id: "jaleshwor", name: "Jaleshwor Municipality", type: "municipality" },
      { id: "bardibas", name: "Bardibas Municipality", type: "municipality" },
      { id: "gaushala", name: "Gaushala Municipality", type: "municipality" },
      { id: "loharpatti", name: "Loharpatti Municipality", type: "municipality" },
      { id: "ramgopalpur", name: "Ramgopalpur Municipality", type: "municipality" },
      { id: "manra_siswa", name: "Manra Siswa Municipality", type: "municipality" },
      { id: "matihani", name: "Matihani Municipality", type: "municipality" },
      { id: "bhangaha", name: "Bhangaha Municipality", type: "municipality" },
      { id: "balawa", name: "Balawa Municipality", type: "municipality" },
      { id: "aurahi", name: "Aurahi Municipality", type: "municipality" },
      { id: "ekdara", name: "Ekdara Rural Municipality", type: "rural-municipality" },
      { id: "sonama", name: "Sonama Rural Municipality", type: "rural-municipality" },
      { id: "samsi", name: "Samsi Rural Municipality", type: "rural-municipality" },
      { id: "mahottari", name: "Mahottari Rural Municipality", type: "rural-municipality" },
      { id: "pipra", name: "Pipra Rural Municipality", type: "rural-municipality" },
    ],
    rautahat: [
      { id: "chandrapur", name: "Chandrapur Municipality", type: "municipality" },
      { id: "garuda", name: "Garuda Municipality", type: "municipality" },
      { id: "gaur", name: "Gaur Municipality", type: "municipality" },
      { id: "baudhimai", name: "Baudhimai Municipality", type: "municipality" },
      { id: "brindaban", name: "Brindaban Municipality", type: "municipality" },
      { id: "devahi_gonahi", name: "Devahi Gonahi Municipality", type: "municipality" },
      { id: "gujara", name: "Gujara Municipality", type: "municipality" },
      { id: "katahariya", name: "Katahariya Municipality", type: "municipality" },
      { id: "madhav_narayan", name: "Madhav Narayan Municipality", type: "municipality" },
      { id: "maulapur", name: "Maulapur Municipality", type: "municipality" },
      { id: "rajpur", name: "Rajpur Municipality", type: "municipality" },
      { id: "ishnath", name: "Ishnath Municipality", type: "municipality" },
      { id: "paroha", name: "Paroha Municipality", type: "municipality" },
      { id: "rajdevi", name: "Rajdevi Municipality", type: "municipality" },
      {
        id: "durga_bhagwati",
        name: "Durga Bhagwati Rural Municipality",
        type: "rural-municipality",
      },
      { id: "yamunamai", name: "Yamunamai Rural Municipality", type: "rural-municipality" },
      { id: "gadhimai", name: "Gadhimai Rural Municipality", type: "rural-municipality" },
      {
        id: "phatuwa_bijayapur",
        name: "Phatuwa Bijayapur Rural Municipality",
        type: "rural-municipality",
      },
    ],
    bara: [
      { id: "kalaiya", name: "Kalaiya Sub-Metropolitan City", type: "sub-metropolitan" },
      {
        id: "jitpur_simara",
        name: "Jitpur Simara Sub-Metropolitan City",
        type: "sub-metropolitan",
      },
      { id: "kolhabi", name: "Kolhabi Municipality", type: "municipality" },
      { id: "nijgadh", name: "Nijgadh Municipality", type: "municipality" },
      { id: "mahagadhimai", name: "Mahagadhimai Municipality", type: "municipality" },
      { id: "simraungadh", name: "Simraungadh Municipality", type: "municipality" },
      { id: "pacharauta", name: "Pacharauta Municipality", type: "municipality" },
      { id: "pheta", name: "Pheta Rural Municipality", type: "rural-municipality" },
      { id: "bishrampur", name: "Bishrampur Rural Municipality", type: "rural-municipality" },
      { id: "prasauni", name: "Prasauni Rural Municipality", type: "rural-municipality" },
      { id: "adarshkotwal", name: "Adarshkotwal Rural Municipality", type: "rural-municipality" },
      { id: "karaiyamai", name: "Karaiyamai Rural Municipality", type: "rural-municipality" },
      { id: "devtal", name: "Devtal Rural Municipality", type: "rural-municipality" },
      { id: "parwanipur", name: "Parwanipur Rural Municipality", type: "rural-municipality" },
      { id: "baragadhi", name: "Baragadhi Rural Municipality", type: "rural-municipality" },
      { id: "suwarna", name: "Suwarna Rural Municipality", type: "rural-municipality" },
    ],
    parsa: [
      { id: "birgunj", name: "Birgunj Metropolitan City", type: "metropolitan" },
      { id: "bahudarmai", name: "Bahudarmai Municipality", type: "municipality" },
      { id: "parsagadhi", name: "Parsagadhi Municipality", type: "municipality" },
      { id: "pokhariya", name: "Pokhariya Municipality", type: "municipality" },
      { id: "bindabasini", name: "Bindabasini Rural Municipality", type: "rural-municipality" },
      { id: "dhobini", name: "Dhobini Rural Municipality", type: "rural-municipality" },
      { id: "chhipaharmai", name: "Chhipaharmai Rural Municipality", type: "rural-municipality" },
      { id: "jagarnathpur", name: "Jagarnathpur Rural Municipality", type: "rural-municipality" },
      { id: "jirabhavani", name: "Jirabhavani Rural Municipality", type: "rural-municipality" },
      { id: "kalikamai", name: "Kalikamai Rural Municipality", type: "rural-municipality" },
      {
        id: "pakaha_mainpur",
        name: "Pakaha Mainpur Rural Municipality",
        type: "rural-municipality",
      },
      {
        id: "paterwasugauli",
        name: "Paterwasugauli Rural Municipality",
        type: "rural-municipality",
      },
      {
        id: "sakhuwa_prasauni",
        name: "Sakhuwa Prasauni Rural Municipality",
        type: "rural-municipality",
      },
      { id: "thori", name: "Thori Rural Municipality", type: "rural-municipality" },
    ],

    // Bagmati Province - More Districts
    kathmandu: [
      { id: "kathmandu_metro", name: "Kathmandu Metropolitan City", type: "metropolitan" },
      { id: "kirtipur", name: "Kirtipur Municipality", type: "municipality" },
      { id: "chandragiri", name: "Chandragiri Municipality", type: "municipality" },
      { id: "tokha", name: "Tokha Municipality", type: "municipality" },
      { id: "tarakeshwar", name: "Tarakeshwar Municipality", type: "municipality" },
      { id: "kageshwari_manohara", name: "Kageshwari-Manohara Municipality", type: "municipality" },
      { id: "budhanilkantha", name: "Budhanilkantha Municipality", type: "municipality" },
      { id: "gokarneshwor", name: "Gokarneshwor Municipality", type: "municipality" },
      { id: "sankharapur", name: "Shankharapur Municipality", type: "municipality" },
      { id: "nagarjun", name: "Nagarjun Municipality", type: "municipality" },
      { id: "dakshinkali", name: "Dakshinkali Municipality", type: "municipality" },
    ],
    lalitpur: [
      { id: "lalitpur_metro", name: "Lalitpur Metropolitan City", type: "metropolitan" },
      { id: "mahalaxmi", name: "Mahalaxmi Municipality", type: "municipality" },
      { id: "godawari", name: "Godawari Municipality", type: "municipality" },
      { id: "konjyosom", name: "Konjyosom Rural Municipality", type: "rural-municipality" },
      { id: "bagmati", name: "Bagmati Rural Municipality", type: "rural-municipality" },
      { id: "mahankal", name: "Mahankal Rural Municipality", type: "rural-municipality" },
    ],
    bhaktapur: [
      { id: "bhaktapur", name: "Bhaktapur Municipality", type: "municipality" },
      { id: "madhyapur_thimi", name: "Madhyapur Thimi Municipality", type: "municipality" },
      { id: "suryabinayak", name: "Suryabinayak Municipality", type: "municipality" },
      { id: "changunarayan", name: "Changunarayan Municipality", type: "municipality" },
    ],
    chitwan: [
      { id: "bharatpur", name: "Bharatpur Metropolitan City", type: "metropolitan" },
      { id: "kalika", name: "Kalika Municipality", type: "municipality" },
      { id: "rapti", name: "Rapti Municipality", type: "municipality" },
      { id: "ratnanagar", name: "Ratnanagar Municipality", type: "municipality" },
      { id: "madi", name: "Madi Municipality", type: "municipality" },
      { id: "ichchhakamana", name: "Ichchhakamana Rural Municipality", type: "rural-municipality" },
    ],
    // More Bagmati Province districts
    dolakha: [
      { id: "bhimeshwor", name: "Bhimeshwor Municipality", type: "municipality" },
      { id: "jiri", name: "Jiri Municipality", type: "municipality" },
      { id: "kalinchok", name: "Kalinchok Rural Municipality", type: "rural-municipality" },
      { id: "melung", name: "Melung Rural Municipality", type: "rural-municipality" },
      { id: "bigu", name: "Bigu Rural Municipality", type: "rural-municipality" },
      { id: "gaurishankar", name: "Gaurishankar Rural Municipality", type: "rural-municipality" },
      { id: "baiteshwor", name: "Baiteshwor Rural Municipality", type: "rural-municipality" },
      { id: "tamakoshi", name: "Tamakoshi Rural Municipality", type: "rural-municipality" },
      { id: "shailung", name: "Shailung Rural Municipality", type: "rural-municipality" },
    ],
    sindhupalchok: [
      { id: "chautara", name: "Chautara Sangachokgadhi Municipality", type: "municipality" },
      { id: "barhabise", name: "Barhabise Municipality", type: "municipality" },
      { id: "melamchi", name: "Melamchi Municipality", type: "municipality" },
      { id: "indrawati", name: "Indrawati Rural Municipality", type: "rural-municipality" },
      { id: "jugal", name: "Jugal Rural Municipality", type: "rural-municipality" },
      {
        id: "panchpokhari",
        name: "Panchpokhari Thangpal Rural Municipality",
        type: "rural-municipality",
      },
      { id: "balephi", name: "Balephi Rural Municipality", type: "rural-municipality" },
      { id: "helambu", name: "Helambu Rural Municipality", type: "rural-municipality" },
      { id: "bhotekoshi", name: "Bhotekoshi Rural Municipality", type: "rural-municipality" },
      {
        id: "lisankhu_pakhar",
        name: "Lisankhu Pakhar Rural Municipality",
        type: "rural-municipality",
      },
      { id: "sunkoshi", name: "Sunkoshi Rural Municipality", type: "rural-municipality" },
      {
        id: "tripurasundari",
        name: "Tripurasundari Rural Municipality",
        type: "rural-municipality",
      },
    ],
    rasuwa: [
      { id: "gosaikunda", name: "Gosaikunda Rural Municipality", type: "rural-municipality" },
      { id: "kalika", name: "Kalika Rural Municipality", type: "rural-municipality" },
      { id: "naukunda", name: "Naukunda Rural Municipality", type: "rural-municipality" },
      { id: "parbatikunda", name: "Parbatikunda Rural Municipality", type: "rural-municipality" },
      { id: "uttargaya", name: "Uttargaya Rural Municipality", type: "rural-municipality" },
    ],
    dhading: [
      { id: "dhunibesi", name: "Dhunibesi Municipality", type: "municipality" },
      { id: "nilkantha", name: "Nilkantha Municipality", type: "municipality" },
      { id: "khaniyabas", name: "Khaniyabas Rural Municipality", type: "rural-municipality" },
      { id: "gajuri", name: "Gajuri Rural Municipality", type: "rural-municipality" },
      { id: "galchhi", name: "Galchhi Rural Municipality", type: "rural-municipality" },
      { id: "gangajamuna", name: "Gangajamuna Rural Municipality", type: "rural-municipality" },
      { id: "jwalamukhi", name: "Jwalamukhi Rural Municipality", type: "rural-municipality" },
      { id: "thakre", name: "Thakre Rural Municipality", type: "rural-municipality" },
      { id: "netrawati", name: "Netrawati Dabjong Rural Municipality", type: "rural-municipality" },
      {
        id: "benighat_rorang",
        name: "Benighat Rorang Rural Municipality",
        type: "rural-municipality",
      },
      { id: "ruby_valley", name: "Ruby Valley Rural Municipality", type: "rural-municipality" },
      {
        id: "tripura_sundari",
        name: "Tripura Sundari Rural Municipality",
        type: "rural-municipality",
      },
      { id: "siddhalek", name: "Siddhalek Rural Municipality", type: "rural-municipality" },
    ],
    nuwakot: [
      { id: "bidur", name: "Bidur Municipality", type: "municipality" },
      { id: "belkotgadhi", name: "Belkotgadhi Municipality", type: "municipality" },
      { id: "kakani", name: "Kakani Rural Municipality", type: "rural-municipality" },
      { id: "kispang", name: "Kispang Rural Municipality", type: "rural-municipality" },
      { id: "tadi", name: "Tadi Rural Municipality", type: "rural-municipality" },
      { id: "likhu", name: "Likhu Rural Municipality", type: "rural-municipality" },
      { id: "myagang", name: "Myagang Rural Municipality", type: "rural-municipality" },
      { id: "shivapuri", name: "Shivapuri Rural Municipality", type: "rural-municipality" },
      { id: "suryagadhi", name: "Suryagadhi Rural Municipality", type: "rural-municipality" },
      { id: "tarkeshwar", name: "Tarkeshwar Rural Municipality", type: "rural-municipality" },
      { id: "dupcheshwar", name: "Dupcheshwar Rural Municipality", type: "rural-municipality" },
      { id: "panchakanya", name: "Panchakanya Rural Municipality", type: "rural-municipality" },
    ],
    kavrepalanchok: [
      { id: "dhulikhel", name: "Dhulikhel Municipality", type: "municipality" },
      { id: "banepa", name: "Banepa Municipality", type: "municipality" },
      { id: "panauti", name: "Panauti Municipality", type: "municipality" },
      { id: "panchkhal", name: "Panchkhal Municipality", type: "municipality" },
      { id: "namobuddha", name: "Namobuddha Municipality", type: "municipality" },
      { id: "mandandeupur", name: "Mandandeupur Municipality", type: "municipality" },
      { id: "khanikhola", name: "Khanikhola Rural Municipality", type: "rural-municipality" },
      { id: "chaurideurali", name: "Chaurideurali Rural Municipality", type: "rural-municipality" },
      { id: "temal", name: "Temal Rural Municipality", type: "rural-municipality" },
      { id: "bethanchok", name: "Bethanchok Rural Municipality", type: "rural-municipality" },
      { id: "bhumlu", name: "Bhumlu Rural Municipality", type: "rural-municipality" },
      { id: "mahabharat", name: "Mahabharat Rural Municipality", type: "rural-municipality" },
      { id: "roshi", name: "Roshi Rural Municipality", type: "rural-municipality" },
    ],
    ramechhap: [
      { id: "manthali", name: "Manthali Municipality", type: "municipality" },
      { id: "ramechhap", name: "Ramechhap Municipality", type: "municipality" },
      { id: "umakunda", name: "Umakunda Rural Municipality", type: "rural-municipality" },
      { id: "khandadevi", name: "Khandadevi Rural Municipality", type: "rural-municipality" },
      { id: "doramba", name: "Doramba Rural Municipality", type: "rural-municipality" },
      { id: "gokulganga", name: "Gokulganga Rural Municipality", type: "rural-municipality" },
      {
        id: "likhu_tamakoshi",
        name: "Likhu Tamakoshi Rural Municipality",
        type: "rural-municipality",
      },
      { id: "sunapati", name: "Sunapati Rural Municipality", type: "rural-municipality" },
    ],
    sindhuli: [
      { id: "kamalamai", name: "Kamalamai Municipality", type: "municipality" },
      { id: "dudhauli", name: "Dudhauli Municipality", type: "municipality" },
      { id: "golanjor", name: "Golanjor Rural Municipality", type: "rural-municipality" },
      { id: "ghyanglekh", name: "Ghyanglekh Rural Municipality", type: "rural-municipality" },
      { id: "tinpatan", name: "Tinpatan Rural Municipality", type: "rural-municipality" },
      { id: "marin", name: "Marin Rural Municipality", type: "rural-municipality" },
      { id: "sunkoshi", name: "Sunkoshi Rural Municipality", type: "rural-municipality" },
      {
        id: "hariharpurgadhi",
        name: "Hariharpurgadhi Rural Municipality",
        type: "rural-municipality",
      },
      { id: "phikkal", name: "Phikkal Rural Municipality", type: "rural-municipality" },
    ],
    makwanpur: [
      { id: "hetauda", name: "Hetauda Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "thaha", name: "Thaha Municipality", type: "municipality" },
      { id: "bhimphedi", name: "Bhimphedi Rural Municipality", type: "rural-municipality" },
      {
        id: "makawanpurgadhi",
        name: "Makawanpurgadhi Rural Municipality",
        type: "rural-municipality",
      },
      { id: "manahari", name: "Manahari Rural Municipality", type: "rural-municipality" },
      { id: "raksirang", name: "Raksirang Rural Municipality", type: "rural-municipality" },
      { id: "bakaiya", name: "Bakaiya Rural Municipality", type: "rural-municipality" },
      { id: "bagmati", name: "Bagmati Rural Municipality", type: "rural-municipality" },
      { id: "kailash", name: "Kailash Rural Municipality", type: "rural-municipality" },
      { id: "indrasarowar", name: "Indrasarowar Rural Municipality", type: "rural-municipality" },
    ],

    // Gandaki Province
    kaski: [
      { id: "pokhara", name: "Pokhara Metropolitan City", type: "metropolitan" },
      { id: "annapurna", name: "Annapurna Rural Municipality", type: "rural-municipality" },
      { id: "machhapuchhre", name: "Machhapuchhre Rural Municipality", type: "rural-municipality" },
      { id: "rupa", name: "Rupa Rural Municipality", type: "rural-municipality" },
      { id: "madi", name: "Madi Rural Municipality", type: "rural-municipality" },
    ],
    tanahu: [
      { id: "vyas", name: "Vyas Municipality", type: "municipality" },
      { id: "shuklagandaki", name: "Shuklagandaki Municipality", type: "municipality" },
      { id: "bhanu", name: "Bhanu Municipality", type: "municipality" },
      { id: "bhimad", name: "Bhimad Municipality", type: "municipality" },
      { id: "abukhaireni", name: "Abukhaireni Rural Municipality", type: "rural-municipality" },
      { id: "devghat", name: "Devghat Rural Municipality", type: "rural-municipality" },
      { id: "rhishing", name: "Rhishing Rural Municipality", type: "rural-municipality" },
      { id: "ghiring", name: "Ghiring Rural Municipality", type: "rural-municipality" },
      { id: "bandipur", name: "Bandipur Rural Municipality", type: "rural-municipality" },
      { id: "myagde", name: "Myagde Rural Municipality", type: "rural-municipality" },
    ],
    // More Gandaki Province districts
    gorkha: [
      { id: "gorkha", name: "Gorkha Municipality", type: "municipality" },
      { id: "palungtar", name: "Palungtar Municipality", type: "municipality" },
      { id: "sulikot", name: "Sulikot Rural Municipality", type: "rural-municipality" },
      { id: "siranchok", name: "Siranchok Rural Municipality", type: "rural-municipality" },
      { id: "ajirkot", name: "Ajirkot Rural Municipality", type: "rural-municipality" },
      { id: "tsum_nubri", name: "Tsum Nubri Rural Municipality", type: "rural-municipality" },
      { id: "dharche", name: "Dharche Rural Municipality", type: "rural-municipality" },
      { id: "bhimsen", name: "Bhimsen Rural Municipality", type: "rural-municipality" },
      { id: "sahid_lakhan", name: "Sahid Lakhan Rural Municipality", type: "rural-municipality" },
      { id: "aarughat", name: "Aarughat Rural Municipality", type: "rural-municipality" },
      { id: "gandaki", name: "Gandaki Rural Municipality", type: "rural-municipality" },
    ],
    manang: [
      { id: "chame", name: "Chame Rural Municipality", type: "rural-municipality" },
      { id: "nason", name: "Nason Rural Municipality", type: "rural-municipality" },
      { id: "narpa_bhumi", name: "Narpa Bhumi Rural Municipality", type: "rural-municipality" },
      {
        id: "manang_ngisyang",
        name: "Manang Ngisyang Rural Municipality",
        type: "rural-municipality",
      },
    ],
    mustang: [
      { id: "gharapjhong", name: "Gharapjhong Rural Municipality", type: "rural-municipality" },
      {
        id: "lo_ghekar_damodarkunda",
        name: "Lo-Ghekar Damodarkunda Rural Municipality",
        type: "rural-municipality",
      },
      { id: "lomanthang", name: "Lomanthang Rural Municipality", type: "rural-municipality" },
      { id: "thasang", name: "Thasang Rural Municipality", type: "rural-municipality" },
      {
        id: "varagung_muktichhetra",
        name: "Varagung Muktichhetra Rural Municipality",
        type: "rural-municipality",
      },
    ],
    myagdi: [
      { id: "beni", name: "Beni Municipality", type: "municipality" },
      { id: "annapurna", name: "Annapurna Rural Municipality", type: "rural-municipality" },
      { id: "dhaulagiri", name: "Dhaulagiri Rural Municipality", type: "rural-municipality" },
      { id: "mangala", name: "Mangala Rural Municipality", type: "rural-municipality" },
      { id: "malika", name: "Malika Rural Municipality", type: "rural-municipality" },
      { id: "raghuganga", name: "Raghuganga Rural Municipality", type: "rural-municipality" },
    ],
    lamjung: [
      { id: "besishahar", name: "Besishahar Municipality", type: "municipality" },
      { id: "madhya_nepal", name: "Madhya Nepal Municipality", type: "municipality" },
      { id: "rainas", name: "Rainas Municipality", type: "municipality" },
      { id: "sundarbazar", name: "Sundarbazar Municipality", type: "municipality" },
      { id: "kvholasothar", name: "Kvholasothar Rural Municipality", type: "rural-municipality" },
      { id: "dudhpokhari", name: "Dudhpokhari Rural Municipality", type: "rural-municipality" },
      { id: "dordi", name: "Dordi Rural Municipality", type: "rural-municipality" },
      { id: "marsyangdi", name: "Marsyangdi Rural Municipality", type: "rural-municipality" },
    ],
    nawalparasi_east: [
      { id: "kawasoti", name: "Kawasoti Municipality", type: "municipality" },
      { id: "gaindakot", name: "Gaindakot Municipality", type: "municipality" },
      { id: "devchuli", name: "Devchuli Municipality", type: "municipality" },
      { id: "madhyabindu", name: "Madhyabindu Municipality", type: "municipality" },
      { id: "hupsekot", name: "Hupsekot Rural Municipality", type: "rural-municipality" },
      { id: "bulingtar", name: "Bulingtar Rural Municipality", type: "rural-municipality" },
      { id: "baudikali", name: "Baudikali Rural Municipality", type: "rural-municipality" },
      {
        id: "binayee_triveni",
        name: "Binayee Triveni Rural Municipality",
        type: "rural-municipality",
      },
    ],
    syangja: [
      { id: "putalibazar", name: "Putalibazar Municipality", type: "municipality" },
      { id: "bhirkot", name: "Bhirkot Municipality", type: "municipality" },
      { id: "galyang", name: "Galyang Municipality", type: "municipality" },
      { id: "chapakot", name: "Chapakot Municipality", type: "municipality" },
      { id: "waling", name: "Waling Municipality", type: "municipality" },
      { id: "arjunchaupari", name: "Arjunchaupari Rural Municipality", type: "rural-municipality" },
      { id: "aandhikhola", name: "Aandhikhola Rural Municipality", type: "rural-municipality" },
      { id: "kaligandaki", name: "Kaligandaki Rural Municipality", type: "rural-municipality" },
      { id: "phedikhola", name: "Phedikhola Rural Municipality", type: "rural-municipality" },
      { id: "harinas", name: "Harinas Rural Municipality", type: "rural-municipality" },
      { id: "biruwa", name: "Biruwa Rural Municipality", type: "rural-municipality" },
    ],
    parbat: [
      { id: "kushma", name: "Kushma Municipality", type: "municipality" },
      { id: "phalebas", name: "Phalebas Municipality", type: "municipality" },
      { id: "jaljala", name: "Jaljala Rural Municipality", type: "rural-municipality" },
      { id: "modi", name: "Modi Rural Municipality", type: "rural-municipality" },
      { id: "bihadi", name: "Bihadi Rural Municipality", type: "rural-municipality" },
      { id: "mahashila", name: "Mahashila Rural Municipality", type: "rural-municipality" },
      { id: "paiyun", name: "Paiyun Rural Municipality", type: "rural-municipality" },
    ],
    baglung: [
      { id: "baglung", name: "Baglung Municipality", type: "municipality" },
      { id: "galkot", name: "Galkot Municipality", type: "municipality" },
      { id: "jaimini", name: "Jaimini Municipality", type: "municipality" },
      { id: "dhorpatan", name: "Dhorpatan Municipality", type: "municipality" },
      { id: "tarakhola", name: "Tarakhola Rural Municipality", type: "rural-municipality" },
      { id: "tamankhola", name: "Tamankhola Rural Municipality", type: "rural-municipality" },
      { id: "nisikhola", name: "Nisikhola Rural Municipality", type: "rural-municipality" },
      { id: "badigad", name: "Badigad Rural Municipality", type: "rural-municipality" },
      { id: "kathekhola", name: "Kathekhola Rural Municipality", type: "rural-municipality" },
      { id: "bareng", name: "Bareng Rural Municipality", type: "rural-municipality" },
    ],

    // Lumbini Province
    rupandehi: [
      { id: "butwal", name: "Butwal Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "siddharthanagar", name: "Siddharthanagar Municipality", type: "municipality" },
      { id: "lumbini_sanskritik", name: "Lumbini Sanskritik Municipality", type: "municipality" },
      { id: "devdaha", name: "Devdaha Municipality", type: "municipality" },
      { id: "sainamaina", name: "Sainamaina Municipality", type: "municipality" },
      { id: "tillotama", name: "Tillotama Municipality", type: "municipality" },
      { id: "gaidahawa", name: "Gaidahawa Rural Municipality", type: "rural-municipality" },
      { id: "kanchan", name: "Kanchan Rural Municipality", type: "rural-municipality" },
      { id: "kotahimai", name: "Kotahimai Rural Municipality", type: "rural-municipality" },
      { id: "marchawari", name: "Marchawari Rural Municipality", type: "rural-municipality" },
      { id: "mayadevi", name: "Mayadevi Rural Municipality", type: "rural-municipality" },
      { id: "omsatiya", name: "Omsatiya Rural Municipality", type: "rural-municipality" },
      { id: "rohini", name: "Rohini Rural Municipality", type: "rural-municipality" },
      { id: "sammarimai", name: "Sammarimai Rural Municipality", type: "rural-municipality" },
      { id: "siyari", name: "Siyari Rural Municipality", type: "rural-municipality" },
      { id: "suddhodhan", name: "Suddhodhan Rural Municipality", type: "rural-municipality" },
    ],
    dang: [
      { id: "tulsipur", name: "Tulsipur Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "ghorahi", name: "Ghorahi Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "lamahi", name: "Lamahi Municipality", type: "municipality" },
      { id: "bangalachuli", name: "Bangalachuli Rural Municipality", type: "rural-municipality" },
      { id: "dangisharan", name: "Dangisharan Rural Municipality", type: "rural-municipality" },
      { id: "gadhawa", name: "Gadhawa Rural Municipality", type: "rural-municipality" },
      { id: "rajpur", name: "Rajpur Rural Municipality", type: "rural-municipality" },
      { id: "rapti", name: "Rapti Rural Municipality", type: "rural-municipality" },
      { id: "shantinagar", name: "Shantinagar Rural Municipality", type: "rural-municipality" },
      { id: "babai", name: "Babai Rural Municipality", type: "rural-municipality" },
    ],
    // More Lumbini Province districts
    kapilvastu: [
      { id: "kapilvastu", name: "Kapilvastu Municipality", type: "municipality" },
      { id: "buddhabhumi", name: "Buddhabhumi Municipality", type: "municipality" },
      { id: "shivaraj", name: "Shivaraj Municipality", type: "municipality" },
      { id: "krishnanagar", name: "Krishnanagar Municipality", type: "municipality" },
      { id: "maharajgunj", name: "Maharajgunj Municipality", type: "municipality" },
      { id: "banganga", name: "Banganga Municipality", type: "municipality" },
      { id: "mayadevi", name: "Mayadevi Rural Municipality", type: "rural-municipality" },
      { id: "yashodhara", name: "Yashodhara Rural Municipality", type: "rural-municipality" },
      { id: "suddhodhan", name: "Suddhodhan Rural Municipality", type: "rural-municipality" },
      { id: "bijaynagar", name: "Bijaynagar Rural Municipality", type: "rural-municipality" },
    ],
    banke: [
      { id: "nepalgunj", name: "Nepalgunj Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "kohalpur", name: "Kohalpur Municipality", type: "municipality" },
      { id: "narainapur", name: "Narainapur Rural Municipality", type: "rural-municipality" },
      { id: "rapti_sonari", name: "Rapti Sonari Rural Municipality", type: "rural-municipality" },
      { id: "baijanath", name: "Baijanath Rural Municipality", type: "rural-municipality" },
      { id: "khajura", name: "Khajura Rural Municipality", type: "rural-municipality" },
      { id: "duduwa", name: "Duduwa Rural Municipality", type: "rural-municipality" },
      { id: "janaki", name: "Janaki Rural Municipality", type: "rural-municipality" },
    ],
    bardiya: [
      { id: "gulariya", name: "Gulariya Municipality", type: "municipality" },
      { id: "rajapur", name: "Rajapur Municipality", type: "municipality" },
      { id: "barbardiya", name: "Barbardiya Municipality", type: "municipality" },
      { id: "thakurbaba", name: "Thakurbaba Municipality", type: "municipality" },
      { id: "madhuwan", name: "Madhuwan Municipality", type: "municipality" },
      { id: "bansagadhi", name: "Bansagadhi Municipality", type: "municipality" },
      { id: "badhaiyatal", name: "Badhaiyatal Rural Municipality", type: "rural-municipality" },
      { id: "geruwa", name: "Geruwa Rural Municipality", type: "rural-municipality" },
    ],
    palpa: [
      { id: "tansen", name: "Tansen Municipality", type: "municipality" },
      { id: "rampur", name: "Rampur Municipality", type: "municipality" },
      { id: "tinau", name: "Tinau Rural Municipality", type: "rural-municipality" },
      { id: "ribdikot", name: "Ribdikot Rural Municipality", type: "rural-municipality" },
      { id: "rambha", name: "Rambha Rural Municipality", type: "rural-municipality" },
      { id: "purbakhola", name: "Purbakhola Rural Municipality", type: "rural-municipality" },
      { id: "nisdi", name: "Nisdi Rural Municipality", type: "rural-municipality" },
      { id: "mathagadhi", name: "Mathagadhi Rural Municipality", type: "rural-municipality" },
      {
        id: "rainadevi_chhahara",
        name: "Rainadevi Chhahara Rural Municipality",
        type: "rural-municipality",
      },
      { id: "bagnaskali", name: "Bagnaskali Rural Municipality", type: "rural-municipality" },
    ],
    nawalparasi_west: [
      { id: "bardaghat", name: "Bardaghat Municipality", type: "municipality" },
      { id: "ramgram", name: "Ramgram Municipality", type: "municipality" },
      { id: "sunwal", name: "Sunwal Municipality", type: "municipality" },
      { id: "susta", name: "Susta Rural Municipality", type: "rural-municipality" },
      { id: "palhi_nandan", name: "Palhi Nandan Rural Municipality", type: "rural-municipality" },
      { id: "pratappur", name: "Pratappur Rural Municipality", type: "rural-municipality" },
      { id: "sarawal", name: "Sarawal Rural Municipality", type: "rural-municipality" },
    ],
    gulmi: [
      { id: "resunga", name: "Resunga Municipality", type: "municipality" },
      { id: "musikot", name: "Musikot Municipality", type: "municipality" },
      { id: "ishma", name: "Ishma Rural Municipality", type: "rural-municipality" },
      { id: "kaligandaki", name: "Kaligandaki Rural Municipality", type: "rural-municipality" },
      { id: "satyawati", name: "Satyawati Rural Municipality", type: "rural-municipality" },
      { id: "chandrakot", name: "Chandrakot Rural Municipality", type: "rural-municipality" },
      { id: "ruru", name: "Ruru Rural Municipality", type: "rural-municipality" },
      { id: "chatrakot", name: "Chatrakot Rural Municipality", type: "rural-municipality" },
      { id: "dhurkot", name: "Dhurkot Rural Municipality", type: "rural-municipality" },
      { id: "madane", name: "Madane Rural Municipality", type: "rural-municipality" },
      { id: "malika", name: "Malika Rural Municipality", type: "rural-municipality" },
      { id: "gulmi_durbar", name: "Gulmi Durbar Rural Municipality", type: "rural-municipality" },
    ],
    arghakhanchi: [
      { id: "sandhikharka", name: "Sandhikharka Municipality", type: "municipality" },
      { id: "sitganga", name: "Sitganga Municipality", type: "municipality" },
      { id: "bhumikasthan", name: "Bhumikasthan Municipality", type: "municipality" },
      { id: "chhatradev", name: "Chhatradev Rural Municipality", type: "rural-municipality" },
      { id: "panini", name: "Panini Rural Municipality", type: "rural-municipality" },
      { id: "malarani", name: "Malarani Rural Municipality", type: "rural-municipality" },
    ],
    pyuthan: [
      { id: "pyuthan", name: "Pyuthan Municipality", type: "municipality" },
      { id: "sworgadwari", name: "Sworgadwari Municipality", type: "municipality" },
      { id: "gaumukhi", name: "Gaumukhi Rural Municipality", type: "rural-municipality" },
      { id: "mandavi", name: "Mandavi Rural Municipality", type: "rural-municipality" },
      { id: "sarumarani", name: "Sarumarani Rural Municipality", type: "rural-municipality" },
      { id: "mallarani", name: "Mallarani Rural Municipality", type: "rural-municipality" },
      { id: "naubahini", name: "Naubahini Rural Municipality", type: "rural-municipality" },
      { id: "jhimruk", name: "Jhimruk Rural Municipality", type: "rural-municipality" },
      { id: "airawati", name: "Airawati Rural Municipality", type: "rural-municipality" },
    ],
    rolpa: [
      { id: "rolpa", name: "Rolpa Municipality", type: "municipality" },
      { id: "triveni", name: "Triveni Rural Municipality", type: "rural-municipality" },
      { id: "paribartan", name: "Paribartan Rural Municipality", type: "rural-municipality" },
      { id: "gangadev", name: "Gangadev Rural Municipality", type: "rural-municipality" },
      { id: "madi", name: "Madi Rural Municipality", type: "rural-municipality" },
      { id: "runtigadi", name: "Runtigadi Rural Municipality", type: "rural-municipality" },
      { id: "lungri", name: "Lungri Rural Municipality", type: "rural-municipality" },
      { id: "sukidah", name: "Sukidah Rural Municipality", type: "rural-municipality" },
      { id: "sunchhahari", name: "Sunchhahari Rural Municipality", type: "rural-municipality" },
      { id: "thawang", name: "Thawang Rural Municipality", type: "rural-municipality" },
    ],
    rukum_east: [
      {
        id: "putha_uttarganga",
        name: "Putha Uttarganga Rural Municipality",
        type: "rural-municipality",
      },
      { id: "bhume", name: "Bhume Rural Municipality", type: "rural-municipality" },
      { id: "sisne", name: "Sisne Rural Municipality", type: "rural-municipality" },
    ],

    // Karnali Province
    surkhet: [
      { id: "birendranagar", name: "Birendranagar Municipality", type: "municipality" },
      { id: "bheriganga", name: "Bheriganga Municipality", type: "municipality" },
      { id: "gurbhakot", name: "Gurbhakot Municipality", type: "municipality" },
      { id: "panchapuri", name: "Panchapuri Municipality", type: "municipality" },
      { id: "lekbesi", name: "Lekbesi Municipality", type: "municipality" },
      { id: "chaukune", name: "Chaukune Rural Municipality", type: "rural-municipality" },
      { id: "barahatal", name: "Barahatal Rural Municipality", type: "rural-municipality" },
      { id: "chingad", name: "Chingad Rural Municipality", type: "rural-municipality" },
      { id: "simta", name: "Simta Rural Municipality", type: "rural-municipality" },
    ],
    jumla: [
      { id: "chandannath", name: "Chandannath Municipality", type: "municipality" },
      { id: "kankasundari", name: "Kankasundari Rural Municipality", type: "rural-municipality" },
      { id: "sinja", name: "Sinja Rural Municipality", type: "rural-municipality" },
      { id: "hima", name: "Hima Rural Municipality", type: "rural-municipality" },
      { id: "tila", name: "Tila Rural Municipality", type: "rural-municipality" },
      { id: "guthichaur", name: "Guthichaur Rural Municipality", type: "rural-municipality" },
      { id: "tatopani", name: "Tatopani Rural Municipality", type: "rural-municipality" },
      { id: "patarasi", name: "Patarasi Rural Municipality", type: "rural-municipality" },
    ],
    // More Karnali Province districts
    dolpa: [
      { id: "thuli_bheri", name: "Thuli Bheri Municipality", type: "municipality" },
      { id: "tripurasundari", name: "Tripurasundari Municipality", type: "municipality" },
      { id: "dolpo_buddha", name: "Dolpo Buddha Rural Municipality", type: "rural-municipality" },
      { id: "she_phoksundo", name: "She Phoksundo Rural Municipality", type: "rural-municipality" },
      { id: "jagadulla", name: "Jagadulla Rural Municipality", type: "rural-municipality" },
      { id: "mudkechula", name: "Mudkechula Rural Municipality", type: "rural-municipality" },
      { id: "kaike", name: "Kaike Rural Municipality", type: "rural-municipality" },
      {
        id: "chharka_tangsong",
        name: "Chharka Tangsong Rural Municipality",
        type: "rural-municipality",
      },
    ],
    mugu: [
      { id: "chhayanath_rara", name: "Chhayanath Rara Municipality", type: "municipality" },
      { id: "khatyad", name: "Khatyad Rural Municipality", type: "rural-municipality" },
      { id: "soru", name: "Soru Rural Municipality", type: "rural-municipality" },
      {
        id: "mugum_karmarong",
        name: "Mugum Karmarong Rural Municipality",
        type: "rural-municipality",
      },
    ],
    humla: [
      { id: "simkot", name: "Simkot Rural Municipality", type: "rural-municipality" },
      { id: "namkha", name: "Namkha Rural Municipality", type: "rural-municipality" },
      { id: "kharpunath", name: "Kharpunath Rural Municipality", type: "rural-municipality" },
      { id: "sarkegad", name: "Sarkegad Rural Municipality", type: "rural-municipality" },
      { id: "chankheli", name: "Chankheli Rural Municipality", type: "rural-municipality" },
      { id: "adanchuli", name: "Adanchuli Rural Municipality", type: "rural-municipality" },
      { id: "tanjakot", name: "Tanjakot Rural Municipality", type: "rural-municipality" },
    ],
    kalikot: [
      { id: "khandachakra", name: "Khandachakra Municipality", type: "municipality" },
      { id: "raskot", name: "Raskot Municipality", type: "municipality" },
      { id: "tilagufa", name: "Tilagufa Municipality", type: "municipality" },
      { id: "pachaljharana", name: "Pachaljharana Rural Municipality", type: "rural-municipality" },
      { id: "sanni_triveni", name: "Sanni Triveni Rural Municipality", type: "rural-municipality" },
      { id: "narharinath", name: "Narharinath Rural Municipality", type: "rural-municipality" },
      { id: "shubha_kalika", name: "Shubha Kalika Rural Municipality", type: "rural-municipality" },
      { id: "mahawai", name: "Mahawai Rural Municipality", type: "rural-municipality" },
      { id: "palata", name: "Palata Rural Municipality", type: "rural-municipality" },
    ],
    dailekh: [
      { id: "narayan", name: "Narayan Municipality", type: "municipality" },
      { id: "dullu", name: "Dullu Municipality", type: "municipality" },
      {
        id: "chamunda_bindrasaini",
        name: "Chamunda Bindrasaini Municipality",
        type: "municipality",
      },
      { id: "aathabis", name: "Aathabis Municipality", type: "municipality" },
      { id: "bhagawatimai", name: "Bhagawatimai Rural Municipality", type: "rural-municipality" },
      { id: "gurans", name: "Gurans Rural Municipality", type: "rural-municipality" },
      { id: "dungeshwor", name: "Dungeshwor Rural Municipality", type: "rural-municipality" },
      { id: "naumule", name: "Naumule Rural Municipality", type: "rural-municipality" },
      { id: "mahabu", name: "Mahabu Rural Municipality", type: "rural-municipality" },
      { id: "thantikandh", name: "Thantikandh Rural Municipality", type: "rural-municipality" },
      { id: "bhairabi", name: "Bhairabi Rural Municipality", type: "rural-municipality" },
    ],
    jajarkot: [
      { id: "bheri", name: "Bheri Municipality", type: "municipality" },
      { id: "chhedagad", name: "Chhedagad Municipality", type: "municipality" },
      { id: "nalgad", name: "Nalgad Municipality", type: "municipality" },
      { id: "barekot", name: "Barekot Rural Municipality", type: "rural-municipality" },
      { id: "kuse", name: "Kuse Rural Municipality", type: "rural-municipality" },
      { id: "junichande", name: "Junichande Rural Municipality", type: "rural-municipality" },
      { id: "shivalaya", name: "Shivalaya Rural Municipality", type: "rural-municipality" },
    ],
    rukum_west: [
      { id: "musikot", name: "Musikot Municipality", type: "municipality" },
      { id: "chaurjahari", name: "Chaurjahari Municipality", type: "municipality" },
      { id: "aathbiskot", name: "Aathbiskot Municipality", type: "municipality" },
      { id: "banfikot", name: "Banfikot Rural Municipality", type: "rural-municipality" },
      { id: "triveni", name: "Triveni Rural Municipality", type: "rural-municipality" },
      { id: "sani_bheri", name: "Sani Bheri Rural Municipality", type: "rural-municipality" },
    ],
    salyan: [
      { id: "shaarda", name: "Shaarda Municipality", type: "municipality" },
      { id: "bangad_kupinde", name: "Bangad Kupinde Municipality", type: "municipality" },
      { id: "kalimati", name: "Kalimati Rural Municipality", type: "rural-municipality" },
      { id: "tribeni", name: "Tribeni Rural Municipality", type: "rural-municipality" },
      { id: "kapurkot", name: "Kapurkot Rural Municipality", type: "rural-municipality" },
      { id: "chhatreshwori", name: "Chhatreshwori Rural Municipality", type: "rural-municipality" },
      { id: "siddha_kumakh", name: "Siddha Kumakh Rural Municipality", type: "rural-municipality" },
      { id: "kumakh", name: "Kumakh Rural Municipality", type: "rural-municipality" },
      { id: "darma", name: "Darma Rural Municipality", type: "rural-municipality" },
      { id: "bagchaur", name: "Bagchaur Municipality", type: "municipality" },
    ],

    // Sudurpaschim Province
    kailali: [
      { id: "dhangadhi", name: "Dhangadhi Sub-Metropolitan City", type: "sub-metropolitan" },
      { id: "tikapur", name: "Tikapur Municipality", type: "municipality" },
      { id: "lamki_chuha", name: "Lamki Chuha Municipality", type: "municipality" },
      { id: "bhajani", name: "Bhajani Municipality", type: "municipality" },
      { id: "godawari", name: "Godawari Municipality", type: "municipality" },
      { id: "ghodaghodi", name: "Ghodaghodi Municipality", type: "municipality" },
      { id: "gauriganga", name: "Gauriganga Municipality", type: "municipality" },
      { id: "janaki", name: "Janaki Rural Municipality", type: "rural-municipality" },
      { id: "joshipur", name: "Joshipur Rural Municipality", type: "rural-municipality" },
      { id: "kailari", name: "Kailari Rural Municipality", type: "rural-municipality" },
      { id: "mohanyal", name: "Mohanyal Rural Municipality", type: "rural-municipality" },
      { id: "bardagoriya", name: "Bardagoriya Rural Municipality", type: "rural-municipality" },
      { id: "chure", name: "Chure Rural Municipality", type: "rural-municipality" },
    ],
    kanchanpur: [
      { id: "bhimdatta", name: "Bhimdatta Municipality", type: "municipality" },
      { id: "punarbas", name: "Punarbas Municipality", type: "municipality" },
      { id: "belauri", name: "Belauri Municipality", type: "municipality" },
      { id: "bedkot", name: "Bedkot Municipality", type: "municipality" },
      { id: "krishnapur", name: "Krishnapur Municipality", type: "municipality" },
      { id: "mahakali", name: "Mahakali Municipality", type: "municipality" },
      { id: "shuklaphanta", name: "Shuklaphanta Municipality", type: "municipality" },
      { id: "beldandi", name: "Beldandi Rural Municipality", type: "rural-municipality" },
      { id: "laljhadi", name: "Laljhadi Rural Municipality", type: "rural-municipality" },
    ],
    // More Sudurpaschim Province districts
    bajura: [
      { id: "badimalika", name: "Badimalika Municipality", type: "municipality" },
      { id: "triveni", name: "Triveni Municipality", type: "municipality" },
      { id: "budhiganga", name: "Budhiganga Municipality", type: "municipality" },
      { id: "budhinanda", name: "Budhinanda Municipality", type: "municipality" },
      { id: "gaumul", name: "Gaumul Rural Municipality", type: "rural-municipality" },
      { id: "jagannath", name: "Jagannath Rural Municipality", type: "rural-municipality" },
      {
        id: "khaptad_chhededaha",
        name: "Khaptad Chhededaha Rural Municipality",
        type: "rural-municipality",
      },
      {
        id: "swamikartik",
        name: "Swamikartik Khapar Rural Municipality",
        type: "rural-municipality",
      },
      { id: "himali", name: "Himali Rural Municipality", type: "rural-municipality" },
    ],
    bajhang: [
      { id: "jayaprithvi", name: "Jayaprithvi Municipality", type: "municipality" },
      { id: "bungal", name: "Bungal Municipality", type: "municipality" },
      { id: "talkot", name: "Talkot Rural Municipality", type: "rural-municipality" },
      { id: "masta", name: "Masta Rural Municipality", type: "rural-municipality" },
      {
        id: "khaptadchhanna",
        name: "Khaptadchhanna Rural Municipality",
        type: "rural-municipality",
      },
      { id: "thalara", name: "Thalara Rural Municipality", type: "rural-municipality" },
      { id: "bitthadchir", name: "Bitthadchir Rural Municipality", type: "rural-municipality" },
      { id: "surma", name: "Surma Rural Municipality", type: "rural-municipality" },
      {
        id: "chhabispathivera",
        name: "Chhabi Spathivera Rural Municipality",
        type: "rural-municipality",
      },
      { id: "durgathali", name: "Durgathali Rural Municipality", type: "rural-municipality" },
      { id: "kedarsyu", name: "Kedarsyu Rural Municipality", type: "rural-municipality" },
      { id: "saipal", name: "Saipal Rural Municipality", type: "rural-municipality" },
    ],
    darchula: [
      { id: "mahakali", name: "Mahakali Municipality", type: "municipality" },
      { id: "shailyashikhar", name: "Shailyashikhar Municipality", type: "municipality" },
      { id: "malikarjun", name: "Malikarjun Rural Municipality", type: "rural-municipality" },
      { id: "apihimal", name: "Apihimal Rural Municipality", type: "rural-municipality" },
      { id: "duhun", name: "Duhun Rural Municipality", type: "rural-municipality" },
      { id: "naugad", name: "Naugad Rural Municipality", type: "rural-municipality" },
      { id: "marma", name: "Marma Rural Municipality", type: "rural-municipality" },
      { id: "lekam", name: "Lekam Rural Municipality", type: "rural-municipality" },
      { id: "byans", name: "Byans Rural Municipality", type: "rural-municipality" },
    ],
    baitadi: [
      { id: "dasharathchand", name: "Dasharathchand Municipality", type: "municipality" },
      { id: "patan", name: "Patan Municipality", type: "municipality" },
      { id: "melauli", name: "Melauli Municipality", type: "municipality" },
      { id: "purchaudi", name: "Purchaudi Municipality", type: "municipality" },
      { id: "sunarya", name: "Sunarya Rural Municipality", type: "rural-municipality" },
      { id: "sigas", name: "Sigas Rural Municipality", type: "rural-municipality" },
      { id: "shivanath", name: "Shivanath Rural Municipality", type: "rural-municipality" },
      { id: "pancheshwar", name: "Pancheshwar Rural Municipality", type: "rural-municipality" },
      { id: "dogdakedar", name: "Dogdakedar Rural Municipality", type: "rural-municipality" },
      { id: "dilasaini", name: "Dilasaini Rural Municipality", type: "rural-municipality" },
    ],
    dadeldhura: [
      { id: "amargadhi", name: "Amargadhi Municipality", type: "municipality" },
      { id: "parshuram", name: "Parshuram Municipality", type: "municipality" },
      { id: "aalital", name: "Aalital Rural Municipality", type: "rural-municipality" },
      { id: "bhageshwar", name: "Bhageshwar Rural Municipality", type: "rural-municipality" },
      { id: "navadurga", name: "Navadurga Rural Municipality", type: "rural-municipality" },
      { id: "ajayameru", name: "Ajayameru Rural Municipality", type: "rural-municipality" },
      { id: "ganyapadhura", name: "Ganyapadhura Rural Municipality", type: "rural-municipality" },
    ],
    doti: [
      { id: "dipayal_silgadhi", name: "Dipayal Silgadhi Municipality", type: "municipality" },
      { id: "shikhar", name: "Shikhar Municipality", type: "municipality" },
      { id: "purbichauki", name: "Purbichauki Rural Municipality", type: "rural-municipality" },
      { id: "badikedar", name: "Badikedar Rural Municipality", type: "rural-municipality" },
      { id: "jorayal", name: "Jorayal Rural Municipality", type: "rural-municipality" },
      { id: "sayal", name: "Sayal Rural Municipality", type: "rural-municipality" },
      { id: "aadarsha", name: "Aadarsha Rural Municipality", type: "rural-municipality" },
      { id: "k_i_singh", name: "K.I. Singh Rural Municipality", type: "rural-municipality" },
      { id: "bogatan", name: "Bogatan Phudsil Rural Municipality", type: "rural-municipality" },
    ],
    achham: [
      { id: "mangalsen", name: "Mangalsen Municipality", type: "municipality" },
      { id: "kamalbazar", name: "Kamalbazar Municipality", type: "municipality" },
      { id: "sanphebagar", name: "Sanphebagar Municipality", type: "municipality" },
      { id: "panchadeval_binayak", name: "Panchadeval Binayak Municipality", type: "municipality" },
      { id: "chaurpati", name: "Chaurpati Rural Municipality", type: "rural-municipality" },
      { id: "mellekh", name: "Mellekh Rural Municipality", type: "rural-municipality" },
      {
        id: "bannigadhi_jayagadh",
        name: "Bannigadhi Jayagadh Rural Municipality",
        type: "rural-municipality",
      },
      { id: "ramaroshan", name: "Ramaroshan Rural Municipality", type: "rural-municipality" },
      { id: "dhakari", name: "Dhakari Rural Municipality", type: "rural-municipality" },
      { id: "turmakhad", name: "Turmakhad Rural Municipality", type: "rural-municipality" },
    ],

    // Add similar entries for other districts as needed
  },
};

export default nepalData;
